name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GPR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GITHUB_TOKEN | docker login --password-stdin -u $GITHUB_ACTOR docker.pkg.github.com

      - name: Build site
        run: docker run -v $(pwd):/site docker.pkg.github.com/qjqqyy/hakyll-latex/hakyll-latex:4.13.2.0 build

      - name: Install SSH Keys
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Push to pages
        uses: JamesIves/github-pages-deploy-action@3.4.7
        with:
          ssh: true
          branch: gh-pages
          folder: _site
